# Generated by Django 3.1.2 on 2020-10-21 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название подразделения')),
            ],
        ),
        migrations.CreateModel(
            name='Military',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('rank', models.CharField(choices=[('Рядовой', 'Рядовой'), ('Ефрейтор', 'Ефрейтор'), ('Младший сержант', 'Младший сержант'), ('Сержант', 'Сержант'), ('Старший сержант', 'Старший сержант'), ('Прапорщик', 'Прапорщик'), ('Старший прапорщик', 'Старший прапорщик'), ('Младший лейтенант', 'Младший лейтенант'), ('Лейтенант', 'Лейтенант'), ('Старший лейтенант', 'Старший лейтенант'), ('Капитан', 'Капитан'), ('Майор', 'Майор'), ('Подполковник', 'Подполковник'), ('Полковник', 'Полковник')], max_length=100, verbose_name='Воинское звание')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.company')),
            ],
            options={
                'verbose_name': 'Военнослужащий',
                'verbose_name_plural': 'Военнослужащие',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тип блюда')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата приема пищи')),
                ('is_done', models.BooleanField(verbose_name='Статус заказа')),
                ('military_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.military', verbose_name='Военнослужащий')),
            ],
        ),
        migrations.CreateModel(
            name='MenuStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mealtime_type', models.CharField(choices=[('Завтрак', 'Завтрак'), ('Обед', 'Обед'), ('Ужин', 'Ужин')], max_length=20)),
                ('week_day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=20)),
                ('products', models.ManyToManyField(to='control.Product')),
            ],
            options={
                'verbose_name': 'Структура меню',
                'verbose_name_plural': 'Структура меню',
            },
        ),
    ]
