# Generated by Django 3.1.2 on 2020-10-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='control.Product'),
        ),
    ]
