# Generated by Django 3.1.2 on 2020-10-29 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='menustructure',
            name='end_time',
            field=models.TimeField(default='15:00', verbose_name='Время окончания приема пищи'),
        ),
        migrations.AddField(
            model_name='menustructure',
            name='start_time',
            field=models.TimeField(default='13:00', verbose_name='Время начала приема пищи'),
        ),
        migrations.AlterField(
            model_name='menustructure',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.menu', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='military',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.company', verbose_name='Название подразделения'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='menu_structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.menustructure', verbose_name='Тип приема пищи'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='control.producttype', verbose_name='Тип блюда'),
        ),
    ]
