# Generated by Django 3.1.2 on 2020-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20201029_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='military',
            name='image',
            field=models.ImageField(default='', upload_to='../../upload', verbose_name='Фотография военнослужащего'),
            preserve_default=False,
        ),
    ]
