# Generated by Django 3.1.2 on 2020-11-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_military_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_done',
            field=models.BooleanField(null=True, verbose_name='Отметка о выполнении заказа'),
        ),
        migrations.AlterField(
            model_name='military',
            name='image',
            field=models.ImageField(upload_to='upload/', verbose_name='Фотография военнослужащего'),
        ),
    ]
